server:
  port: 8081
  servlet:
    session:
      timeout: 120m
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    threads:
      min-spare: 30
kakao:
  baseUri: https://dapi.kakao.com
  uri: /v2/search/blog
  token: KakaoAK 7905d8d8bf472226bd6f6c0900b0b4b5
